### PR TITLE
Ignore spaces after items in "Needs:" and "Tags:" lists

### LINKED ISSUE #364: A space behind a `Needs: ` specification item validates the requirement
# Description
If you put a space behind any item of a `Needs: ` specification, it validates the requirement.
Which means, that the requirement is not considered a defect anymore, despite the fact that none of the needed further specifications have been made, e.g. dsn, req, ... 

These lead to a validated requirement:
- `Needs: req , dsn `
- `Needs: req `
- `Needs: req, dsn `
- `Needs: req ,dsn`
- `Needs: req,dsn `

Only two ways to not run into this bug:
- `Needs: req,dsn`
- `Needs: req, dsn`

## Steps to Reproduce
1. Write a requirement, it doesn't matter which, I tried a `feat`
2. Add the `Needs: ....` line with the variants i mentioned.

## Expected behavior
I expect that the parser correctly parses a comma separated list and trims the spaces from all items and actually even if an unknown element is in the list, doesnt just set the requirement to 'done'.

# Environment
- OFT: 3.7.0
- OS: Arch Linux 6.4.12-arch1-1
- Java Version: openjdk 11.0.20.1 2023-08-24

## Additional context
It's easy to fall into this trap through a simple typo, which could be avoided through proper parsing.
Especially when you have a lot of requirements to track, you will never witness the simple typo of a space behind one of the `Needs:` items...

### PR DESCRIPTION
**Pull request by sambishop**
Closes #364
This PR addresses issue 364: https://github.com/itsallcode/openfasttrace/issues/364

I noticed that "Tags" lists behave the same way, so I updated them as well.

### CODE REVIEW

**Review by kaklakariada — APPROVED** [review]

**Comment by sambishop** [comment]
@kaklakariada, thank you for reviewing my PR.  But it's been stuck for over a day now waiting for the SonarCloud analysis, and I suspect that it's never going to complete.  Do you know how to get that step to run?

Also, I think this is a great project, so I thought I'd try addressing a few open issues as a way of showing my appreciation.  So let me know if there's anything I can improve.  I plan to open one PR per issue.  Thanks.

**Comment by kaklakariada** [comment]
Hi @sambishop ,
thank you very much for your PR, we really appreciate that! I don't know how to solve the issue with the Sonar analysis. The token for Sonar is not available in external PR so we run it only when the token is available:

```yml
    - name: Sonar analysis
      shell: bash
      if: ${{ env.DEFAULT_OS == matrix.os && env.DEFAULT_JAVA == matrix.java && env.SONAR_TOKEN != null }}
      run: |
        mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
I guess the pragmatic solution would be to merge the PR anyway after a review.

Another thing: I would like to add an entry to the changelog for your changes. I will do that directly in your PR if that's OK for you.

**Comment by kaklakariada** [comment]
I added tests and found a bug with parsing the `Tags:` field and fixed it.
@redcatbear Please also have a look at my changes.

**Comment by sambishop** [comment]
I've never used Sonar on a public repo before.  I've tried adding a Sonar token secret to my forked repo, to see if that allows it to run.  And I've addressed the only two outstanding Sonar issues.  Let's see what happens.

Thanks again for your help, @kaklakariada!

File: importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ enum MdPattern
             + SpecificationItemId.ID_PATTERN
             + ").*?"),
     ID("`?((?:" + SpecificationItemId.ID_PATTERN + ")|(?:" + SpecificationItemId.LEGACY_ID_PATTERN + "))`?.*"),
-    NEEDS_INT("Needs:\\s*(\\w+(?:,\\s*\\w+)*)"),
+    NEEDS_INT("Needs:(\\s*\\w+\\s*(?:,\\s*\\w+\\s*)*)"),
```
Comment (redcatbear) [inline importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java:40]: :+1:

File: importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+                + "  * " + COVERED_ID1 + "\n" //
+                + " + " + "[Link to baz2](#" + COVERED_ID2 + ")\n" //
+                + "\nDepends:\n\n" //
+                + "  + " + DEPENDS_ON_ID1 + "\n" //
+                + "  - " + DEPENDS_ON_ID2 + "\n" //
+                + "\nComment:\n\n" //
+                + COMMENT_LINE1 + "\n" //
+                + COMMENT_LINE2 + "\n" //
+                + "\nNeeds: " + NEEDS_ARTIFACT_TYPE1 //
+                + " , " + NEEDS_ARTIFACT_TYPE2 + " ";
```
Comment (redcatbear) [inline importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java:74]: Good catch!

File: importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java [hunk 3]
```diff
@@ -0,0 +1,247 @@
...
+    }
+
+    private List<SpecificationItem> runImporterOnText(final String text)
+    {
+        final BufferedReader reader = new BufferedReader(new StringReader(text));
+        final InputFile file = StreamInput.forReader(Paths.get(FILENAME), reader);
```
Comment (redcatbear) [inline importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java:80]: No intermediate file on the file system. I like it.

File: importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java [hunk 4]
```diff
@@ -0,0 +1,247 @@
...
+                + COMMENT_LINE1 + "\n" //
+                + COMMENT_LINE2 + "\n" //
+                + "\nNeeds:\n" //
+                + "   * " + NEEDS_ARTIFACT_TYPE1 + "\n"//
+                + "+ " + NEEDS_ARTIFACT_TYPE2 + "\n" //
+                + "\nTags: " + TAG1 + ", " + TAG2;
+
+        // + "\nTags:\n" //
+        // + " * " + TAG1 + "\n" //
+        // + " + " + TAG2 + "";
```
Comment (redcatbear) [inline importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java:165]:
```suggestion

        // + "\nTags:\n" //
        // + " * " + TAG1 + "\n" //
        // + " + " + TAG2 + "";
```

Please remove commented code.

File: importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownImporter.java [hunk 5]
```diff
@@ -55,6 +51,20 @@ void testIdentifyTitle()
         assertMismatch(MdPattern.TITLE, "Title", "Title #", " # Title");
     }
 
+    @Test
+    void testIdentifyNeeds()
+    {
+        assertMatch(MdPattern.NEEDS_INT, "Needs: req, dsn", "Needs:req,dsn", "Needs:  \treq , dsn ");
+        assertMismatch(MdPattern.NEEDS_INT, "Needs:");
```
Comment (redcatbear) [inline importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownImporter.java:58]: We should wrap all of these with `assertAll(()-> ... )` so that all sub-asserts are always executed. Provides better debugging output.

**Review by redcatbear — CHANGES_REQUESTED** [review]
Looks really good! Thanks for the PR.

Couple small improvements suggested.

File: doc/changes/changes.md [hunk 6]
```diff
@@ -1,5 +1,6 @@
 # Changes
 
+* [3.7.2](changes_3.7.2.md)
 * [3.7.1](changes_3.7.1.md)
```
[the remark this answers is not in the document]
Comment (kaklakariada) [reply doc/changes/changes.md:4]: OFT 3.7.1 was released to Maven Central (https://repo1.maven.org/maven2/org/itsallcode/openfasttrace/openfasttrace-core/3.7.1/) and GitHub (https://github.com/itsallcode/openfasttrace/releases/tag/3.7.1), so the next release should be 3.7.2.
